/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a financial-report analysis
         * @description Accepts one to five PDF, XLSX, or CSV files. The Phase 0 MSW handler intercepts this request in the browser; no file leaves the browser.
         */
        post: operations["createAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get analysis processing status */
        get: operations["getAnalysisStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the completed analysis result */
        get: operations["getAnalysisResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/evidence/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the evidence binding for a dashboard item
         * @description Returns the fact and calculation IDs associated with the clicked item. The Phase 0 drawer resolves those IDs against the cached analysis result, which contains source records and deterministic calculation provenance.
         */
        get: operations["getEvidenceDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            retryable: boolean;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        AnalysisLifecycleStatus: "accepted" | "validating" | "extracting" | "normalizing" | "calculating" | "detecting_exceptions" | "generating_explanation" | "completed" | "failed";
        /** @enum {string} */
        CompletionOutcome: "completed" | "completed_with_review_flags";
        /**
         * @description Field-level availability and quality. Partial analysis coverage is represented by ExtractionSummary, not by this enum.
         * @enum {string}
         */
        ValueStatus: "verified" | "not_present" | "not_readable" | "ambiguous" | "conflicting" | "failed";
        /** @enum {string} */
        Confidence: "high" | "medium" | "low";
        /** @enum {string} */
        UnitScale: "units" | "thousands" | "millions";
        /** @enum {string} */
        FileKind: "pdf" | "xlsx" | "csv";
        /** @enum {string} */
        ProcessingStageKey: "validate" | "extract" | "normalize" | "calculate" | "detect" | "explain";
        /** @enum {string} */
        ProcessingStageState: "pending" | "active" | "completed" | "warning" | "failed";
        /** @enum {string} */
        MetricFormat: "currency" | "percentage" | "ratio";
        /** @enum {string} */
        AnomalySeverity: "high" | "medium" | "low";
        /** @enum {string} */
        InsightTone: "strength" | "concern" | "neutral";
        CreateAnalysisResponse: {
            analysis_id: string;
            document_ids: string[];
            status: components["schemas"]["AnalysisLifecycleStatus"];
            status_url: string;
            result_url: string;
        };
        ExtractionSummary: {
            targeted_fields: number;
            extracted_fields: number;
            manual_review_count: number;
        };
        ProcessingStage: {
            key: components["schemas"]["ProcessingStageKey"];
            title: string;
            description: string;
            state: components["schemas"]["ProcessingStageState"];
            progress_percent: number;
            logs: string[];
        };
        AnalysisStatusResponse: {
            analysis_id: string;
            status: components["schemas"]["AnalysisLifecycleStatus"];
            completion_outcome?: components["schemas"]["CompletionOutcome"] | null;
            progress_percent: number;
            active_stage?: components["schemas"]["ProcessingStageKey"] | null;
            message: string;
            stages: components["schemas"]["ProcessingStage"][];
            extraction_summary: components["schemas"]["ExtractionSummary"];
            error?: components["schemas"]["ApiError"] | null;
        };
        DocumentSummary: {
            id: string;
            name: string;
            size_bytes: number;
            size_label: string;
            kind: components["schemas"]["FileKind"];
            page_or_sheet_count: number;
        };
        AnalysisSummary: {
            analysis_id: string;
            company: string;
            registration_id: string;
            currency: string;
            unit_scale: components["schemas"]["UnitScale"];
            current_period: string;
            prior_period: string;
            /** Format: date */
            statement_date: string;
            documents: components["schemas"]["DocumentSummary"][];
            extraction_summary: components["schemas"]["ExtractionSummary"];
            completion_outcome: components["schemas"]["CompletionOutcome"];
        };
        SourceLocation: {
            document_id: string;
            document_name: string;
            locator: string;
            raw_value: string;
            excerpt: string;
            /** Format: date-time */
            extracted_at: string;
        };
        FinancialPeriodValue: {
            id: string;
            period: string;
            /** @description Decimal string in the declared unit scale, or null when unavailable. */
            value: string | null;
            currency: string;
            unit_scale: components["schemas"]["UnitScale"];
            sources: components["schemas"]["SourceLocation"][];
        };
        ConflictCandidate: {
            period: string;
            value: string;
            source: components["schemas"]["SourceLocation"];
        };
        FinancialField: {
            id: string;
            key: string;
            label: string;
            status: components["schemas"]["ValueStatus"];
            confidence: components["schemas"]["Confidence"];
            requires_manual_review: boolean;
            current: components["schemas"]["FinancialPeriodValue"];
            prior: components["schemas"]["FinancialPeriodValue"];
            absolute_change: string | null;
            percentage_change: string | null;
            conflict?: components["schemas"]["ConflictCandidate"] | null;
            note?: string | null;
            evidence_id: string;
        };
        Calculation: {
            id: string;
            label: string;
            formula: string;
            input_value_ids: string[];
            substitution: string;
            result: string;
            /** @enum {string} */
            unit: "percentage" | "ratio" | "currency";
            period: string;
            evidence_id: string;
        };
        KpiMetric: {
            id: string;
            label: string;
            format: components["schemas"]["MetricFormat"];
            current: string;
            prior: string;
            absolute_change: string;
            percentage_change: string;
            higher_is_better: boolean;
            status: components["schemas"]["ValueStatus"];
            calculation_id: string;
            evidence_id: string;
        };
        RatioComparison: {
            id: string;
            label: string;
            /** @enum {string} */
            unit: "percentage" | "ratio";
            current: string;
            prior: string;
            absolute_change: string;
            percentage_change: string;
            higher_is_better: boolean;
            current_calculation_id: string;
            prior_calculation_id: string;
            evidence_id: string;
        };
        TrendPoint: {
            period: string;
            metric: string;
            value: string;
            format: components["schemas"]["MetricFormat"];
        };
        Anomaly: {
            id: string;
            rule_id: string;
            title: string;
            detail: string;
            severity: components["schemas"]["AnomalySeverity"];
            fact_ids: string[];
            calculation_ids: string[];
            follow_up: string;
            requires_manual_review: boolean;
            evidence_id: string;
        };
        Insight: {
            id: string;
            title: string;
            narrative: string;
            fact_ids: string[];
            calculation_ids: string[];
            tone: components["schemas"]["InsightTone"];
            evidence_id: string;
        };
        AnalysisResult: {
            summary: components["schemas"]["AnalysisSummary"];
            fields: components["schemas"]["FinancialField"][];
            calculations: components["schemas"]["Calculation"][];
            kpis: components["schemas"]["KpiMetric"][];
            ratios: components["schemas"]["RatioComparison"][];
            trends: components["schemas"]["TrendPoint"][];
            anomalies: components["schemas"]["Anomaly"][];
            insights: components["schemas"]["Insight"][];
            follow_up_questions: string[];
        };
        EvidenceDetail: {
            evidence_id: string;
            title: string;
            subtitle?: string | null;
            fact_ids: string[];
            calculation_ids: string[];
            narrative?: string | null;
            follow_up?: string | null;
        };
    };
    responses: {
        /** @description Analysis does not exist */
        AnalysisNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ANALYSIS_NOT_FOUND",
                 *       "message": "The requested analysis could not be found.",
                 *       "retryable": false
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Evidence binding does not exist */
        EvidenceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "EVIDENCE_NOT_FOUND",
                 *       "message": "The requested evidence trail could not be found.",
                 *       "retryable": false
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Analysis has not completed */
        ResultNotReady: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "RESULT_NOT_READY",
                 *       "message": "The analysis result is not ready yet.",
                 *       "retryable": true
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description At least one file exceeds 20 MB */
        FileTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FILE_TOO_LARGE",
                 *       "message": "Each file must be 20 MB or smaller.",
                 *       "retryable": false
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description At least one file has an unsupported type */
        UnsupportedFileType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNSUPPORTED_FILE_TYPE",
                 *       "message": "FinTrace AI accepts searchable PDF, XLSX, and structured CSV files.",
                 *       "retryable": false
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description File count or request shape is invalid */
        InvalidFileSet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_FILE_SET",
                 *       "message": "Select between one and five files for one analysis.",
                 *       "retryable": false
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unexpected processing or server failure */
        InternalFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "PROCESSING_FAILED",
                 *       "message": "The analysis could not be completed. Start a new analysis and try again.",
                 *       "retryable": true
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Opaque analysis identifier. */
        AnalysisId: string;
        /** @description Opaque evidence-binding identifier. */
        EvidenceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            /** @description Analysis accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "analysis_id": "anl_demo_001",
                     *       "document_ids": [
                     *         "doc_pdf_001",
                     *         "doc_xlsx_001"
                     *       ],
                     *       "status": "accepted",
                     *       "status_url": "/api/v1/analyses/anl_demo_001/status",
                     *       "result_url": "/api/v1/analyses/anl_demo_001/result"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateAnalysisResponse"];
                };
            };
            413: components["responses"]["FileTooLarge"];
            415: components["responses"]["UnsupportedFileType"];
            422: components["responses"]["InvalidFileSet"];
            500: components["responses"]["InternalFailure"];
        };
    };
    getAnalysisStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque analysis identifier. */
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current processing state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatusResponse"];
                };
            };
            404: components["responses"]["AnalysisNotFound"];
            500: components["responses"]["InternalFailure"];
        };
    };
    getAnalysisResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque analysis identifier. */
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed dashboard result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            404: components["responses"]["AnalysisNotFound"];
            409: components["responses"]["ResultNotReady"];
            500: components["responses"]["InternalFailure"];
        };
    };
    getEvidenceDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque analysis identifier. */
                analysisId: components["parameters"]["AnalysisId"];
                /** @description Opaque evidence-binding identifier. */
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence binding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceDetail"];
                };
            };
            404: components["responses"]["EvidenceNotFound"];
            500: components["responses"]["InternalFailure"];
        };
    };
}
