import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    "node_modules/**",
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Python is checked independently by Ruff, mypy, and pytest.
    "backend/**",
    // Generated by MSW; its header explicitly requires consumers not to edit it.
    "public/mockServiceWorker.js",
  ]),
])

export default eslintConfig
